/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.io.IOException;
import sistemamemoria.Proceso; 
import sistemamemoria.SistemaMemoria; 

import javax.swing.table.DefaultTableModel; 
import javax.swing.DefaultListModel; 
import javax.swing.DefaultComboBoxModel; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;


/**
 *
 * @author Luciano Pinedo
 */
public class Interfaz extends javax.swing.JFrame {
public static SistemaMemoria app; 
public static  Interfaz interfaz = new Interfaz(); 
private procesoNuevo procesonuevo = new procesoNuevo();
private DefaultTableModel modeloOriginal; 
public static ordenEjecucion ordenejecucion = new ordenEjecucion();


    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        
        initComponents();
        app = new SistemaMemoria(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Agregar proceso: ");

        jButton2.setText("Secuencial");

        jButton3.setText("Variada");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar Proceso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Memoria Principal");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marco", "Proceso", "Pagina"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Número de Páginas", "Páginas Principal", "Páginas Virtual", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jLabel3.setText("Proceso a Ejecutar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton4.setText("Alerta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Deseo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setText("Memoria Virtual (Procesos listos y en ejecución)");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Paginas"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel5.setText("Procesos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5))))
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
      procesonuevo.setVisible(true); 
      
          
      
      
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         String proceso = (String) jComboBox1.getSelectedItem();
        String[] division = proceso.split(":"); 
        int numeroProceso = Integer.parseInt(division[1].trim()); 
         Proceso proceso2 = app.buscarProceso(numeroProceso); 
         
        app.ejecutarProceso(proceso2);
        
       
            
        
        actualizarMemoriaPrincipal(); 
       
        if (app.revisarFinal(proceso2)) {
             
                 
                 app.finalizarProceso(proceso2);
                 
            
            removerMemoriaPrincipal(numeroProceso); 
            DefaultTableModel a = (DefaultTableModel) jTable4.getModel(); 
            a.getDataVector().clear(); 
                 
            actualizarTablaProcesos(proceso2);
            actualizarComboBox(); 
          
            actualizarMemoriaVirtual(); 
            
        }
        actualizarTablaProcesos(proceso2);
        actualizarComboBox(); 
        
        actualizarMemoriaVirtual(); 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    try { 
        app.alerta();
    } catch (UnsupportedAudioFileException ex) {
        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
    } catch (LineUnavailableException ex) {
        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    try {
        app.deseo();         // TODO add your handling code here:
    } catch (UnsupportedAudioFileException ex) {
        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
    } catch (LineUnavailableException ex) {
        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

   
    
    public void actualizarMemoriaPrincipal() {
        
        DefaultTableModel memoriaTablaDinamica = modeloOriginal; 
        for (int i = 0; i < app.getMemoriaPrincipal().getTamaño();  i++) {
            if (app.getMemoriaPrincipal().getMemoriaPrincipal()[i] != null) {
            String proceso = "Proceso " + app.getMemoriaPrincipal().getMemoriaPrincipal()[i].getProcesoPadre().getNumeroProceso();
            String pagina  = "Pagina "  + app.getMemoriaPrincipal().getMemoriaPrincipal()[i].getNumeroPagina(); 
            memoriaTablaDinamica.setValueAt(proceso, i, 1); 
            memoriaTablaDinamica.setValueAt(pagina, i , 2); 
        }
        }
        
        jTable2.setModel(memoriaTablaDinamica); 
        
    }
    
    public void removerMemoriaPrincipal(int numProceso) {

        String proceso = "Proceso " + numProceso;
        for (int i = 0; i < app.getMemoriaPrincipal().getTamaño(); i++) {
        if (modeloOriginal.getValueAt(i, 1).equals(proceso)) {
            modeloOriginal.setValueAt("",i ,1);
            modeloOriginal.setValueAt("", i, 2); 
        }
            }
        jTable2.setModel(modeloOriginal);
    }
    public void actualizarComboBox() {
         interfaz.jComboBox1.setEnabled(true); 
        DefaultComboBoxModel comboBoxDinamico = new DefaultComboBoxModel(); 
        for (int i = 0; i < app.getAllProcesos().size(); i++) {
            String labelProceso = "Proceso: " + app.getAllProcesos().get(i).getNumeroProceso(); 
            comboBoxDinamico.addElement(labelProceso);
           
        }
        for (int j = 0; j < app.getAllProcesos().size(); j++) {
             if (app.getAllProcesos().get(j).isFinalizado()) {
                System.out.println("Esta finalizado");
                comboBoxDinamico.removeElementAt(app.getAllProcesos().get(j).getNumeroProceso());
            }
        }
        jComboBox1.setModel(comboBoxDinamico);
        
    }
    
    public void añadirTablaProcesos(Proceso proceso) {
        int totalPaginas = proceso.getTotalPaginas().length; 
        int totalPrincipal = 0;
        int totalVirtual = totalPaginas; 
        DefaultTableModel procesosTablaDinamica = (DefaultTableModel) jTable3.getModel();
        String nombreProceso = Integer.toString(proceso.getNumeroProceso()); 
        String numPagTotal = Integer.toString(totalPaginas); 
        String pagPrincipal = Integer.toString(totalPrincipal); 
        String pagVirtual = Integer.toString(totalVirtual);
        String Estado = "Nuevo";
        procesosTablaDinamica.addRow(new Object[] { nombreProceso, numPagTotal, pagPrincipal, pagVirtual, Estado});
        
        
    }
    
    public void actualizarTablaProcesos(Proceso proceso) {
        int totalPaginas = proceso.getTotalPaginas().length; 
        int totalPrincipal = app.procesoTotalPaginasPrincipal(proceso);
        int totalVirtual = totalPaginas - totalPrincipal; 
        DefaultTableModel procesosTablaDinamica = (DefaultTableModel) jTable3.getModel();
        
        
        String pagPrincipal = Integer.toString(totalPrincipal); 
        String pagVirtual = Integer.toString(totalVirtual);
        
        for (int i = 0; i < procesosTablaDinamica.getRowCount();  i++) {
            
            if (!procesosTablaDinamica.getValueAt(i, 4).equals("Nuevo") && !procesosTablaDinamica.getValueAt(i, 4).equals("Finalizado")) {
                 procesosTablaDinamica.setValueAt("Listo", i, 4); 
            }
        }
        
        procesosTablaDinamica.setValueAt(pagPrincipal, proceso.getNumeroProceso() , 2);
        procesosTablaDinamica.setValueAt(pagVirtual,proceso.getNumeroProceso() , 3);
        procesosTablaDinamica.setValueAt("Ejecutando", proceso.getNumeroProceso(), 4); 
        
        
        
           
       
        if (proceso.isFinalizado()) {
            procesosTablaDinamica.setValueAt("Finalizado", proceso.getNumeroProceso(), 4); 
        }
        
    }
    
    public void actualizarTodo() {
        
       
        actualizarComboBox(); 
        actualizarMemoriaPrincipal(); 
        actualizarMemoriaVirtual(); 
        
    }
    
    public void iniciar() {
        
         modeloOriginal = (DefaultTableModel) jTable2.getModel(); 
         for (int i = 0; i < app.getMemoriaPrincipal().getTamaño(); i++) {
  
           
                modeloOriginal.addRow(new Object[] {Integer.toString(i), "", ""}
                        
                );
        }
    }
    
    public void actualizarMemoriaVirtual() {
        DefaultTableModel memoriaVirtualDinamica = (DefaultTableModel) jTable4.getModel();
       
        memoriaVirtualDinamica.getDataVector().clear();
        
        if (app.getAllProcesos().isEmpty()) {
            
            memoriaVirtualDinamica.addRow(new Object[] {"", ""});
        }
         memoriaVirtualDinamica.getDataVector().clear();
         
        for (int i = 0; i < app.getAllProcesos().size(); i++){
            String Numeroproceso = "Proceso " + app.getAllProcesos().get(i).getNumeroProceso(); 
            Proceso proceso = app.getAllProcesos().get(i); 
            
            String paginas = "";
            
            for (int j = 0; j < app.getAllProcesos().get(i).getTotalPaginas().length; j++) {
                int k = 0; 
               for (k = 0; k < app.getMemoriaPrincipal().getMemoriaPrincipal().length; k++) {
                   if (proceso.getTotalPaginas()[j] == app.getMemoriaPrincipal().getMemoriaPrincipal()[k] ) {
                      k =  app.getMemoriaPrincipal().getMemoriaPrincipal().length ; 
                       System.out.println("La pagina esta");
                   }
                   
               }
               if (k != app.getMemoriaPrincipal().getMemoriaPrincipal().length  + 1 ) {
                       
                       paginas = paginas + proceso.getTotalPaginas()[j].getNumeroPagina() + ", "; 
                   }
            }
          memoriaVirtualDinamica.addRow(new Object[] {Numeroproceso, paginas} );
        }
         jTable4.setModel(memoriaVirtualDinamica);
        
    }
    
    public static void main(String args[]) throws InterruptedException {
       Inicio inicio = new Inicio();  
     
      
       inicio.setVisible(true);
      
       while (!inicio.isIniciado()) {
       Thread.sleep(200); 
         
        
       }
       
        inicio.setVisible(false); 
        interfaz.setVisible(true);
        interfaz.jComboBox1.setEnabled(false); 
        app.iniciar(inicio.enviarInicial()); 
        interfaz.iniciar(); 
      
       
       
  
        
        
        
        
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        }); */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

/*
ENCONTRASTE A CHANG 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oo+ooo++ooo++ooooooooooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++osyhyhhhhhhhhhhhhhhhhhhhhdmmmmmmmmmmmddmddhhddmmmmmNm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo+++++++++++++++++++++++++++++++++++++++++++++++osyhhhhhhhhhhhhhhhhhhhhhhdmmmmddmmmmmmmmdddddddmmmmmm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooosooooooooosssssoooosoooooooooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++++++++osyhhhhhhhhhhhhhhhhhhhhhhddmmmmmmmmmmmmmmmmmdmmmNmmmm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooossssyyyyyyyyyyyyyyyyyyyyyyyyssssssssooooooooooooooooooooooooooo++++++++++++++++++++++++++++++++++++oosyhhhhhhhhhhhhhhhhhhhhhhdmmmmNNmmmmmmmmmdddddddmmmmm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooosssyyhhhhhhhhhhhhddddddddddddddhhhhhyyyyssssoooooooooooooooooooooooooo+++++++o+++++++++++++++++++++++++++osyhhhhhhhhhhhhhhhhhhhhhhddddmmmmmmmmmmmddddhddhdmmmm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooossyhhdddddddmmmmmmmmmmmmmdmmmmmmmmmdddddddhhyyyssssoooooooooooooooooooooooooooo++++++++++++++++++++++++++++osyyyhhhhhhhhhhhhhhhhhhhhddmdmmmmmmmmmmmddddhhhdmmmmm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooosssyhddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddhhhyysssssoooooooooooooooooooooo++++++++++++++++++++++++++++osyhhhhhhhhhhhhhhhhhhhhhhdmmmmmmmdddddddddddddddmmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooosyyhddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddhhhyyysssoooooooooooooooooo+++++++++++++++++++++++++++osyhhhhhhhhhhhhhhhhhhhhhhdmmNmNmmdddddddddddmmmmmmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooossyhdddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddddhhysssoooooooooo++++oo+++++++++++++++++++++++++oosyhhhhhhhhhhhhhhhhhhhhhhdmmNNNNmmddddmmmmmmmmmmmmmmm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooossyhhdmmmmmmmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddhhyssoooooooo++++oo+++++++++++++++++++++oo+++ooyhhhhhhhhhhhhhhhhhhhhhhhdmmmmmmmmmdmmmmmmmmmmmmmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooosssyhddmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhysssooooo+++++++++oo++++++++++++++++++++++oyhhhhhhhhhhhhhhhhhhhhhhhdmmmmmmmNmmddmmmmmNmmmmmmdd
+++++++++++++++++++++++++++++++++++++++/+++++++++++++++++++++++++++oooooooossyhhdmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmNNNmmmmmmmmmmmmmddyssooooo+++++++++oo++++++++++++++++++++++oyhhhhhhhhhhhhhhhhhhhhhhdmmNmmdmmmmmmmmNmmmmmmmmmmdd
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooosssyhddmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmdhysooooooo++++++ooooo++++++++++++++++++ooyhhhhhhhhhhhhhhhhhhhhhhhdmmmmddmmNNNmmmmmmmmmmNNmmd
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++o++++ooossyhhddmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmNmmmmmmmmmmmmddhssoooo+++++++ooooo++++++++++++++oo++ooyhhhhhhhhhhhhhhhhhhhhhhhdmddddmNNNNNmmmmdmmmmmNNNmm
+++++++++++++++++++//////////+++++++++++++++++++++++++++++++++o+++ooosyhdddmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmNmmmmmmmmmmmmmmdhysooooo+++++ooooo++++++++++oooooo+oooyhhhhhhhhhhhhhhhhhhhhhhhhdddddmNNmmmmmmmdddmmNNNNNN
+++++++++++++++////////////////////////+++++++++++++++++++++++oo++osyhddmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmdhyysooo++++ooooooooooo+ooooooooo+++ooyhhhhhhddhhhhhhhhhhhhhhhhdddmmmmmmddmmmmmmmmmNNNNNN
++++//////+++++////////////////////////+++++////++++++++++++++oooosyhdmmmmmmmmmmmmmmmmNmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmdhyoooo+++ooooooooooo+ooooooooo++++oyhhhhhddddhhhhhhhhhhhhhhdddmmmmddddddmmmmddmmmmmmmm
+++///////++++//////////////////////////////+++++++++++++++++oooosydmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmdhysoooooooooooooooo+oooooooo++++ooshhdddddddhhhhhhhhhhhhhhdddmmmmmdmmmdddddddmmmmmmmm
+++/////////////////////////////////////////+++++++++++++++++ooosyhdmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmdhysoooooooooo++++++oooo++++++++oosyhdddddhddhhhhhhhhhhhhhddddddmmmmmNmmmdddmmmmmmmmm
+++////////////////////////////////////////++++++++++++++++++oosyhdmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNNNmmmmmmmmmNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmdhysooooooooo++++++++++++++++++oosyhhdddddddhhhhhhhhhhhhhddmmmmmmmmmmmmmdddmNNNmmmmm
+++++/////////////////////////////////////++++++++++++++++o+oosyhdmmmmmmmmmmmmmmmmmmmmmNNNNNNNmNNNNmmmmmmmmNNNNmmmmNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddhsooo++++++++++++++++++++++ooosyhdddddddddhhhhhhhhhhhddmmmmmmmmmmddmmmmmmNNmmddmm
+++++/////////////////////////////////////++++++++++++++++o+osyddmmmmmmmmmmmmmmmmmmmmmmNNNNNNmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhsooo+++++++++++++++++++++oooshhddddddddddhhhhhhhhhhhddmmmmmmmmmdddmmmNNNNmmdddd
++++++++++/////////////////////////////////+++++++++++++++oosydmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddhsooo++o++++++++++++++++++oosyhddddddddddhhhhhhhhhhhdmmmmmmmmmmddmmmmmmmmmddhhh
++++++++++/////////////////////////////////+++++++++++++++osyhmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmddysooooo+++++++++++++++++++osyhdddddddddddhhhhhhhhhhddmmNNNNNmmmmmmmmmmmmddhddd
+++++++++///////////////////////////////////++++++++++++oosyhdmmmmmmmmmmmmddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhysoooo+++++++++++++++++++ooyhhddddddddddhhhhhhhhhhddmmNNNmmmmmmmdmmmNmmdddddm
++/++///////////////////////////////////////+++++++++++oosyhddmmmmmmmdddmddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdhysooo+++++++++++++++++++ooyhhdddddddddddhddhhhhhddmmmmmmmmmmmmmmmNNNmmdhhddm
++/+++++++//////////////////////////////////////++++++++osyddmmmmmmmddddddddddddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddmmmmddmmmmmmmmmmmmmmdddmmdhysooo+++++++++++++++++++ooyhhdddddddddddhhdhhhhhddmNNmmmNNNNNNNNmNNNmdhhhddm
++++++++++//////////////////////////////////////++++++++oshdddmdmmddddddddddddddddmmmmmmmmmmmmmmmmmmmdddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmdddddhhhdddddddddddmmmmmmmmmmmmmmmddhyooooo+++++++++++++o+++ooyhddddddddddddhhhhhhhhhdmNNNNNNNNNNNNmmmNNmddddmmm
+++++++++++++++/////////////////////////////////+++++++osyhdddmdddddddddddddddddddmmmmmmmmmmmmmmmmmddddhddddmmmmmmmmmmmmmmmmmmddddddddddhhhhhhyyyyyyhhyyyyhhhhddddmmmmmmmmddddhysoooo+++++++++++++oo+++oshdddddddddddhhhhhhhhhhddmmNNNNNNNNmmmmmmmddhddmmm
++/++++++++++++//////////////////////////////////++++++osyddddddddddddddddmmmddddmmmmmmmmddddmmmdddhhhhhhhhhddhhddddhhhhhhhhhhhhhhhyyyyyyyyyyyyyssssyyysssyyyyyyhhddmmmmmmmdddhysoooo+++++++++++++oooooosyhddddddddddhhhhhhhhhhhdddmNNNNNNNNNmmmmmmmmmmmmm
+++++++++++++++//////////////////////////////////+++++ooyhhhhddddddddddddmmmmmmddmmmmmddddhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyhhhhyyyyyyyyyyyyyysssssssssssssssysyyyyyyyhddmmmmmdddhysooooo+o++++++++oooooooosyhdddddddddddhhhhhhhhhhdddmmNNNNNNNNNmmNNmmNNmNNm
+++++++++++++++//////////////////////////////////+++++ooyhhhhhdddddddmmmmmmmmmmmdmmdddhhyyyyyyssssssyyyssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysssssssssssssssssssssssyyhdddmdddddhysoooooo+++++++ooooooooosyhdddddddddddhhhhhhhhhddmmmmmmmmmNNNNNNNNmNNNmmmm
++++++++++++++++++++++++/////////////////////////+++++osyhhhhhhddddmmmmmmmmmmmmddddhyssssooooossssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyysssssssssssssssssssssssssssssyhddddddddhysoooooooooooooooooooooosyhdddhddhhhddhhhhhhhhhdmmmmmmmmmmNNNNNmNNNNNNNNmm
++++++++++++++++++++++++///////////////+++++++++++++++osyhhhhhhdddmmmmmmmmmmmdhyyyysooooooooooooossssssssssssssyysyyyyyyyyyyyyyyyyyyyyyysssssssssssssssssssssssssssssyyhdddddddhysoooooooooooooooooooooosyhdddhddhhhdddhhhhhhhhhmmmmmmmmmmmmmmmmmmmmNNNmmm
++++++++++++++++++++/////++++/////+++++++++++++++++++oosyhhhhhddddmmmmmmmmmmdhyssoooo+ooooooooooosossssssssssyyyssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssyyhhddddddhysoooooooooooooooooooooosyhddddddhhhddddhhhhhhhdmNNNNNNNmmmddddmmNNNNNmmmm
++++++++++++++++++++////+++++++++++++++++++++++++++++oosyddddddddmmmmmmmmmddhysoooo++++ooooooooooosssssssssssyyssyyyyyyyyyyysssyyyyyyyyyyyyyyyyyyyhhhhyyyyyyyyssssssyyyyhhdddmdhysoooooooooooooooooooooosyhddddhhhhhhddddhhhhhhdmNNNNNmmmmmddmmmmNNNNNNmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++oosydddddddmmmmmmmddddhysoooo++++++ooooooooosssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhyyyyyyyyyyssyyyyyyhdddddhyssooooooooooooooooooooosyhdddddddddddddddhhhhhddmNNNNNNNNmmmmmmmmmNNNNNmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++oosydddmmmmmmmmmdddddhysoo+++++++++++ooooosssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyhddddyssoooooooooooooooooooooosyhdddddddddddddddhhhhhddmmmmmmmmmmmNNNmmmNNNNNmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++oosyddmmmmmmmmmdddddhysooo+++++++++++oosssssyyyyyyyyhhhhhhyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhyyyyyyyyyysyyyyyyyhhddhyssoooooooooooooooooooooosyhdddddddddddddddhhhhhhdmmmmmdmmmmNNNNNNNNmddmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++oosyhdmmmmmmmddddddhysoo++++++++++++oosssyyyyyhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhyyyyyyyyyyssssysyyyyhhhyssooooooooooooooooooooooooyhdddddddddddhhhhhhhhhddmmmmmmmmmmmNNNNNNNmmddmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++oooyhdmmmmmmmddddhyyso++++++++++++oooosssyyyyhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhyyyyyyyyyyyysssssyyyyyyyssoooooooooooooooooooooooooshdddddddddhhhhhhhhhhhddmmmmmmmNNNNNNNmmmmmmmmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++ooosyddmmmmmddhhyssooo+++++++++++ooooosssyyyhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhyyyyyyyyyyyysssssyyyyyyssooooooooooooooooooooooooooshdddddddddhhhhddhhhhhhddmmmmmmNmmmNNmmmmmmNNmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++ooshhdmddddhyssoooo++++++++++++oooosssssyyyyhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhyyyyyyyyyyyysssssyyyyyyssooooooooooooooooooooooooooyhddddddddhdhhdddhhhhhhddmmmmNNNmmmmmmmmmmNNNmmmm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++oosydddddhyssooooo++++++++++++ooooossssyyyyyhhhhhhhhhhhhhhyyyyysyssyyyssssyysyyyhhhhhhhhdhhhhhhyyyyyyyyyyyyssssyyyyyysoooooooooooooooooooooooooooyhdddddddddddddhhhhhhhhhdmmNNNNNNNmmmmmmmmNNNNmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++oosyhdddyssooooo++++++++++++++ooooossssyyyyyhhhhhhhhhhhhhhyyysssssssssssssssyyyhhhhhdddddddddhhhhhyyyyyyyyysssssyyyysssssssoooooooooooooo++++oooshdddddddddddddhhhhhhhhddmmNNNNNNNNNNNNNNNNmNNNNN
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooosydhyssooooo++++++++++++++ooooossssyyyyyhhhhhddhhhhhhhyyysssssssssssssssyyyhhhdddddmmmmmdhhhhhhhhhyyyyysssssyyyysssssyyssoooooooooooo+++++oosydddddddddddddhhhhhhhhddmmNNNNNNNNNNNNNNNNNNNNNN
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooyyysoooooo++++++++++++ooooooossssyyyhhddddddddddhhhhyysssssssssssssssssyyyhhddddmmmmmmmdhhyhhhhhhyyyssssssyyyyyyyyyyyysoooooooooooo++++++ooydddddddddddddhhhhhhhhddmmmNNNNNNNNNNNNNNNNNNNNN
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooossssoooooo+++++++++oooooooossssyyyyhddmmddddddddhhhyysssossssssssssssssyyhhddddddmmmmmddhyyyhhhyyyyyyssssyyyyyyyyhhhyssoooooooooooo+++++ooyddddddddddddddhhhhhhhdddmmmNNNNmmNNNNNNmmmmmmNN
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooo+++++++++ooooooossyyyyyyyhdmmmmddddddhhhyyyssooosssssssssssssyyyhhhhdddddmdddhyyyyyyyyyyyyyssssyyyyyyyhhhhyssoooooooooooo+++++ooyddddddddddddddddddddhhddmmmdmmNNNNNNNNNNNmmdmmN
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooo+++++++++++oooooossyyyyssyhdmmmdddhhhhhhhyyssooooossssssssssssyyyyhhhhddddddhhhyyyyyyyssssssssssyyyyyyyyhhhhssooooooooooooooo+++oyddddddddddddddddddddhddmmmmmmNNNNNNmmmmmmmmmddd
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooo++++++++++++oooooossssssssyhdddddhhhhhhyyysssooooossssssssssssyyyyyhhhhhhhhhhhyyyyyyysssssssssssyyyyyyyyhhhhssooooooooooooooo++ooyhddddddddddddddddddddddmNmmNNNNNNNmmmmmddmmmmdd
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++o+oooooooooooooo+++++++++++++oooooooosssssyyhhhhhhhhhyyysssooooooossssssssssssyyyyyyyyyyyyyyyyyyyyysssssssssssssyyyyyyyyhhhysooooooooooooooooooooyhddddddddddddddddddddddmNNNNNNNNNNNmmmmmmmNNmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooosssoooooooooo+++++++++++++++++ooooooosssyyyyyyyyyyyyssoooooooooosssssssssssssyyyyyyyyyyyyyyyyyysssssssssssssyyyhhhhyyhhyysooooooooooooooooooooyhddddddddddddddddddddddmNNNNNNmmNNNNmNmmmmmNNmm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooosyyysooooooooo+++++++++++++++++oooooooosssssyyyyyyssssooooooooooooossssssssssssyyyyyyyyyyyyyyyyyssssssssssssssyyhhhhhyhyyysooooooooooooooooooooshddddddddddddddddddddddmNNNmmmmmNNNmmNNNmmmmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++osyhhysoooooooo+++++++++++++++++++ooooooooosssssyyssssoooooooooooooosssssssssssssssssyyyyyyyyyyyyysssssssssssssyyyhhhhhhyyysoooooooooooooooooooooshdddddddddddddddddhddddmNNNNmmmmNNNmmNNNNmmmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++osyhhysoooooooooo+++++++++++++++++ooooooooossssssssssooooooooooooooossssssssssssssssssyyyyyyyyyyyysssssssssssssyyyyhhhhhyyssooooooooooooooooooooosyddddddddddddddddhhddddmNNNNNNNmmNmmmmNNNmmmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++osyhhysooooooooooo+++++++++++++++oooooooooossssssssssooooooooooooooossssssssssssssssssyyyyyyyyyssssssssssssssssyyyyhhhhhyssooooooooooooooooooooooshdddddddddddddddhhhdhddmNNNNmNmmmmmmmmmmmmmmmNN
o++++++++++++++++++++++++++++++++++++++++++++++++++++++++oosyhysssssosssssoo++++++++++++oooooooooooossssssssssssoooooooooooossssssssssssssssyyyyyyyyyysssssssssssssssssssyyyhhhhhyssooooooooooooooooooooosshddddddddddddddddhhdhdddmNmmmmmmmmmmmmmmmmmNNNN
o++++++++++++++++++++++++++++++++++++++++++++++++++++++++oosyyhyssssyyyyyysoo+++++++++++ooooooooooooossssssssssssooooooooooossssssssssssssssyyyyyyyyyysssssssssssssssssssyyyyyyyyyssooooooooooooooooooooosyhddddddddddddddddhhhddddmmmmmmmmmmmmmmmmmmmNNNN
o+++++++++++++++++++++++++++++++++++++++++++++++++++++++++oosyyyssyyyyyyyysoo+++++++++++++++ooooooooosssssssssssssssoooooooosssssssssssssssssyyyyyyyyysssssssssssssssssssyyyyyyyssssooooooooooooooooooooossyhdddddddddddddddhhhhhhddmmmmNNmNNNNmmmmmmmNNNN
o++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oosyyssyyyyyyyssoo++++++++++++++++oooooooossssssssssssssssooosooosssyyysyyyyssssssyyyyyyyyyyysssssssssssssssssyyyyyyyssssoooooooooooooooooooooosyhddddddddddddddddddhhhdmmmmmmmmNNNmmmmmmmmmmNm
o++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooosssyyyyyyyyssoo+++++++++++++++++ooooooossssssssyyyyyssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyysssssssssssssssssyyyyyysssoooooooooooooooooooooossyhdddddddddddddddhhhhhhdmNNNNNNNNNNNmmmmmmmmmmm
o++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooossyyyyyyssooo++++++++++++++++++oooooosssssssyyyysssssyyyyyyyyyhyyyyyhhhhhyyyyyyyyyyyyyssssssssssssssssssssssysssoooooooooooooooooooossoosyhddddddddddddddddhhhhhhmNNNNNNNNNNNNNNNNNNNNNN
o+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooossyyyyssssoo+++++++++++++++++oooooooossssssyyyyssssyyhddhhhhyyyhhyyhddhhhyyyyyyyyyyyssssssssssssssssssssssssssooooooooooooooooooooossossyhdddddddddddddddhhhhhhdmmNNNNmmNNNNNNNNNNNNNNN
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooosssssssssoo+o++++++++++++ooooooooooossssssyyyssssyyhhhhyyyyyhhyyyyhhhyyyyyyyyyyyyssssssssssssssssssssssssssooooooooooooooooooooosssossyhdddddddddddddddhhhhhhdmNNNNNNNNNNNNNmmmNNmmmm
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooo+++++++++++ooooooooooossssssssssssssyyyyysyyyyyyyyyyyyyyyyyyyyyyyyysssssssssssssssssssyssssssoooooooooooooooooooooossossyhdddddddddddddddhhhhhhddmNNNNNNNNNNNNmmmmNmmmm
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooo+++++++ooo+++ooo+oooooooosssssssssssssssssssyyyyyyyyyyyysssyyyyyyyyyyssssssssssssssssssssssssoooooooooooooooooooooooooossshdddddddddddddddhhhhhhddmNNNNNNNNNNNmmmmmNmmmN
o+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooo+oooooooo+++++ooooooooooossssssssssssssssssyyyyyyyyyyysssssssssyyyyyssssssssssssssssssssssooooooooooooooooooooooooooooosshdddddddddddddddhhhhhhhdmNNNNNNNNNNNmmmmmmmmNN
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooo++oooooooooooooooo+++++++++oooooooossssssssssssssssyyyyyyyyyyyyssssssssyyyyyyysssssssssssssssssssssooooooooooooooooooooooooooooosshdddddddddddddddhhhhhhddmmNNNNNNNNNNNmmNNNNmmN
o+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oo+++oooooooooooooooooooo+++++ooooossoosssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssssssooooooooooooooooooooooooooooooooosyhddmmddddddddddhhhhhhdddmNNNNNNNNNNNNNNNNmmmm
o+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++o+++++ooooooooooooooooooo++++oooooosssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyssssssssssooooooooooooooooooooooooooooooooosyhddmmdddddddddhhhhhhhhddmNNNNNNNNNNNNNNNNNNmm
o++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooo++ooooooossssssssssssssssyyyyyhhhhhhhhhyyyyyhhhhhhhhhhhyyyyyyyyyssssssssoooooooooooooooooooooooooooooooooosyhddmmdddddddddhhhhhhhhddNNNNmmNNmNNNNNNNNNNNN
o++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++o++++++++++++++ooooo+++ooooosssssssyyyysssyyyyyyhhhhhhhhhhhhhhhhhhhhhhhddhhhhyyyyyyysssssssooooooooooooooooooooooooooooooooooosyhdddddddddddddhhhhhhhhhdmNNNmmmmmmmNNNNNNNNNN
o+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooo+++ooooosssyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhdddhhhhyyyyyyssssssoooooooooooooooooooooooooooooooooooooyhdddddddddddddhhhhhhhhhdmNNNmmmmmmmNNNNNmNNNN
oo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooosssyyyhhhhyyyyyyyyyyhhhhhhhhhhhhhhhyhhhhhhhhhhhhhhhhyyyyyssssssooooooooooooooooooooooooooooooooooooosyddddddddddddhhhhhhhhhddmNNmmmmNmmmmNNNNNNNNN
oo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooossyyyhhhhhyyyysyyyyyyyyyhhhhhhhhyyyyyyyyyhyyhhhhhhhhyyyyyssssssooooooooooooooooooooooooooooo+ooooooosyddddddddddddhhhhhhhhdddmmmmmmNNNmmmNNNNNNNNN
oo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooosssyyyhhyyyysssssssssyyyyyyhhhhhhyyyyyyyyyyyyyhhhhhhyyyyyysssssoooooooooooooooooooooooooooooooooooooosyhdddddddddddhhhhhhhhdddmmmmmmNNNNNNNNNNNNNNN
oo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooossssyyyyyysssssssssssyyyyhhhhhhhhyyyyyyyyyyyyyyhhhyyyyyyyysssooooooooooooooooooooooooooooooooooo+oooosyhddddddddddhhhhhhhhhdddmNNNNNNNNNNNNNNNNNNNN
oo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooossssssssssssssssssssyyhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyyyssooooooooooooooooooooo+++++oooo+++oo++++oosyhdddddddddhhhhhhhhhhhddmNNNNNNNNNNNmNNNNNNNN
oooo++++++++++++++++++++++++o++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooosssssssssssssssssssyyhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyssooooooooooooooooooooo+++++++++++++++++++++oshdddddddddhhhhhhhhhhhddmNNNNNNNNNNNNNmmmNNNN
oooo++++++++++++++++++++++++o++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooossssssssssssssssyyyyhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyyyyyyssoooooooooooooooooooo+o+++++++++++++++++++ooyhddddddddhhhhhhhhhhhhhdmmNNNNNNNNNNNNNNNNNNN
oooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooossssssssssssyyyyyhhhhhhhhhhhhhhhhhhhyhyyyyyyyyyyyyyyyssooooooooooooooooooo++o++++++++++++++oooooosshddddddhhhhhhhhhhhhhhddmNNNNNNNNNNNNNNNNNNNN
oooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooosssssssssssyyyyyhhhhhhhhhhhhhhhhhhhhyhyyyyyyyyyyyyyyyssooooooooooooooooooooo++oooooooo++++ooooooosyhddddddhhhhhhhhhhhhhhddmNNNNNNNNmmNNNNNNNNNN
oooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooosssssssssssyyyyhhhhhhhhhhhhhhhhhhhhhhhhyyyyyyyyyyyyyyssooooooooooooooooooooo++++++oooooo+oooooooosyyhdddddhhhhhhhhhhhhhhhddNNNNNNNNNNNNNNNNNNNN
oooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooososssssssssyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhyyhyyyyyyyyysoooooooooooooooooooooo++++++ooooooooooooooosyyhddddddhhhhhhhhhhhhhdddNNNNNNNNNNNNNNNNNNNN
oooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooooooooooooooooooooosossssssssssyyyyyyyhhhhhddddhhhhhhhhhhhhhhhhhhhhyyyyyssoooooooooooooooooooo+++++++oooooooooooooosssyhdddddddhhhhhhhhhhhhddmNNNNNNNNNNNNNNNNNmmm
oo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooo++oooooooooooooooooooosssssssssssssyyyyyyhhhhhhhddhhdhhhhhhhhhddhhhhyyhyyyyyysooooooooooooooo++++++++++++ooooooooooossssssyhdddddddhhhhhhhhhhhhhddNNNNNNNNNNNNNNNNNNmm
ooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ooooooo++oooooooooooooooooooossssssssssssssssyyyhyhhhhhhhhhhhhhhhhhhhddhhhhyyyyyyyyyssooooooooooooo+++++++++++++oooooooooosssssssyddddddddhdhhhhhhhhhhhddmNNNNNNNNNmNNNmmNNNm
ooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooosssssssssssssssssyyyyhhhhhhhhhhhhhhhhhhhhddhhhhhhhhhhhhhyysooooooooooooo++++++++++ooooooooooooossssssyhdddddddhhhhhhhhhhhhhddmNNNNNNNNmmmmmNNNNNN
ooooo++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooossssssssssssyyyyyyyhhhhhhhhhhhhhhhhhhhhhdhhhhhhhhhhhhhhysoooooooooooooooo++++oooooooooooooooossssssyhdddddddhhhhhhhhhhhhhddmNNNNNNNNNNmmNNNNNNN
ooooo+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++oo+++++++++ooooooooooooosssssoooooooooooossssssssssssyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhysoooooooooooooooo+++ooooooooooooooooossssssyhdddddddhhdhhhhhhhhhhddmNNNNNNNNNNNNNNNNNNN
oooo++++o+++++++++++++++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooosyyyysooooooooooossssssssssssyyyyhhhhhhhhhhhhddhhhhhhhhhhhhhhhhhhhhyhhhhhysooooooooooooooooooooooooooooooooossssssssyhdddddddhhhhhhhhhhhhdddmNNNNNNNNNNNNNNNNmmm
ooooo+++o++++++++++++++++++++++++++++++++++++++++++++++++o+++oooooooooooooooooooooooooooossyhhyssooooooooossssssssssssssyyyhhhhdddddhhddhhhhhhhhhhhhhhhhhhhyyyhhhdhysooooooooooooooooooooooooooooooooossssssssyhdddddddhhdhhhhhhhhhdddmmNNNNNNNNNNNNNNNNNN
ooooo++++++++++oooo+++++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooossyhhhyssoooooosssssssssssssssssyyyyhhhdddddddddhhhhhhhhhhhhhhhyyyyyyyhhhhhysoooooooooooo++oooooooossoosssoossssooosssyhdddddddhhhddddddhhhddddmNNNNNNNmmNNNNNNNNN
ooooo++++oooooooooo+++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooshhhhysssooosssssssssssssssssssssyyyhhhdhhhhhhhhhhhhhhhhhhhhhhyyyyyyyhhhhysoooooo+++++oooooooooosssssssssssssssooosssyhhdddddddddddddddddhhdddmNNNNNNNNNNNNNNNNNN
ooooo++++oooooooooo+++++++++++++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooshhdhysssooosssssssssssssssssssssyyyhhhhhhhhhhhhhhhhhhhhhhhhhhyyyyhyyhhhhysooooo++++++oooooooooosssssssssssssssooosssyhhddddddddddddddddddhddmmmNNNNNNNNNNNNNNNNN
ooooooooooooooooooooooooooooo++++++++++++++++++++++++++++oooooooooooooooooooooooooooooooosyhddhysssossssssssssssssssssssyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyhhhhhhyysooooo++++++ooooooooooossssssssssssssssssssyhddddddddddddddddddddddmmNNNNNNNNNNNNNNNNNN
ooooooooooooooooooooooooooooo++++++++++++++++++++++++++++ooooooooooooooooooooooooooooooooosyhdhyyssssssssssssssssssssssssyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyssooo++++++++ooooooooooossssssssssssssssssssyhhdddddddddddddddddddddmmNNNNNNNNNNNNNNNNNN
ooooooooooooooooooooooooooooo+++++++++++++++++++ooooo++ooooooooooooooooooooooooooooooooooossyhhhyyssssssssssssysssssssssyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhysooo+++++++++oooooooooooosssssssssssssssssssyyhddddddddddddddddhhdddmNNNNNNNNNNNNNNNNNNN
soooooooooooooooooooooooooooooooooooooo+++++ooooooooooooooooooooooooooooooooooooooooooooooossyhhhhyysssssssssyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhysooo+++++++++ooooooooooooooosssssssssssssssssyyhdddddddddddddddddddmmmNNNNNNNNNNNNNNNNNNN
ooooooooooooooooooooooooooooooooooooooo++++oooooooooooooooooooooooooooooooooooooooooooooooooosyhhhhyyyssssysyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyssooo+++++++++ooooooooosooooooosssssssssssssssyyhdddddddddddddddmmmmmmmNNNNNNNNNNNNNNNNNNN
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosyyhhhyyyysyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyssoooo++++++++++ooooooooooooooooooossssssssssssyyhdddmmdddddddddmmNNNNmmNNNmNNNmmNNNNNNNNNm
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossossyyhhyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhysoooooo+++++++++oooooooooooooooooooooossssssssssyyhddmmmmmmmmmdmmmNNNNNNNNNNNNNNNNNNNNNNNNNm
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossyyyhyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyysoooooo++++++ooooooooooooooooooooooooosssssssssyyyhhddmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNN
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossyyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhhyssoooooo+++++ooooooooooooooooooooooosssssssssssyyhhhhddmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossssyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhddhysooooooooooooooooooooooooooooooooooossssssssssssyyhhhhhdmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
ssoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosssssyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdddhysooooooooooooooooooooooooooooooooooosssossssssssssyhdddddmmNNNNNNNNmmmmmmmmmmNNNNNNNNNNNNNNNNNN
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossssssyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhyssoooooooooooooooooooooooooooooooooooosoossssssssyyyhddmmmmmNNNNNNNmmmmmmmmmmmmNNNNNNNNNNNNNNNNN
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosssssssyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhysssooooooooooooooooooooooooooooooooooooooosssssssyyhhddmmNNNNNNNNNNmmmmmmmmmmmmmNNNNmmmmNNNNNNNNN
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosssssssssyyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhysssooooooooooooooooooooooooooooooooooooooooosssssyhhddmmmNNNNNNNNNNmmmmmmmmmmddmmmNNNNNmmNNNNNNMNN
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosssssssssssssyyhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdhhhyssssoooooooooooooooooooooossooooooooooosssossssyyyhhddmmmNNmNNNNNNNNmmmmmmmmmdddmmNNNNNNNNNNNNNNNNN
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooossssssssssssssssssyyyyhhhhhhhhhhhhhhhhhhhhhhhdddhhhhhyssssoooooooooosssooooooooossssssssssssssssssssyhhhhddmmNNNNmNNNNNNNNNmmmmmmddmdmmNNNNNNNNNNNNNMMMMN
oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssyyyyyhhhhhhhhhhhhhhhhhhddddhhyysssssoooooooooosssoooooooooosssssssssssssssssyyhhddddmmNNNNNNNNNNNNNNNmmmmmmddmdmmNNNNNNNNMMMMMMMMMN
sssooooooooooooooooooooooooooooooooooooooooooooooooooossssoooooooooooooooooooooooosooossssssosssssssssssssssssssssssssssyyyyyhhhhhhhhhhhhhhddhhhhhhhysssssssssssssssssssssssssoooossssssssssssssyyyhhdddmmmmNNNNNNNNNNNNNNNNmmmmmdddmmmmNNNNNNNNMMMMNNMNNN
sssssoooooooooooooooooooooooooooooooooooooooooooooooossssssssssssssssoosssssssssssssossssssssssssssssssssssssssyssssyyyyyyyyyyhhhhhhhhhhhhhhhhhhhhhyyyyysssssssssssssssssssssysssssyyyyyyyyyyhhhhhddddmmmNNNNNNNNNNNNNNNNNNmmmmmdddmmmmmNNNNNNNNNMMMMMNNNN
sssssoooooooooosoooooooooossssssssooooossssssssssssssssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyhhyyhhhhhhhhhhhhdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddmmNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmNNNNNNNNNMMMMNNNNN
yysssssssssssssssssssyyyyyyyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhhhhddddddddddmddddmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNN
hhhhhhhhhhyhhhdhhhdddddddddddddddddddddddddddmmdddmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmNNNNNNNNNNNNNmmNNNN
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmNNNNmmNNmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNmmNmmmmmmmmmmmmmmmmmmmmNNNNNmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmdmmmmmmmmmmNNNNNNNNNNNNmmmmNNN
NmmmmmmmmmmmmmmmmmNmmmmmmmmmmmmmNNmmmmmNNNNNNNmmmmmNNNNNNNNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNN
NNmmNNNmmmmmmmmmmmNNmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNmmNmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmdmmNNNNNNNNMMMMMNNNNNN
NmmmNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmdmmmmmmmmmmmmNNMMNNNMMMMMMMMMNNNN
NmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNNNNNNNNNmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmNNNMMNNNNNMMMMMMMNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmNNNNNNNmmmmNNmNNNmmmmmmNNNNNNNNNmmNNmmmNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmNNNMMMMNNNNNNMMMMMNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNmNNNNmmmmmNNNNmmmmNmmmmNmmmmmmmNNNmmmmmmmmmmmmmNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmdmmmmmmmmmmmNNNMMMMMNNNNNNNMMMMNNNNNN
NNNNNNNNNNNNNNNmNNNNNNNNNNNNNNNNNNNNNmmNNNNNNmmmmmmmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNmmmmmmmNmNNmmmNmmNmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmNNNNNNMMMMNNNNNNNNNNMMNNNNN
NmmNNmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNmmmmmmmmmmmmmNmmmmmmmmmmmmmNNNmmmNmmNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNNNNNNNNNNNNNNmmmddddmmmmmmNNNNNNNNNNNMMNNNNNNNNNNNNNNNNNN
*/