/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import sistemamemoria.SistemaMemoria; 
import javax.swing.table.DefaultTableModel; 
import javax.swing.DefaultListModel; 
import javax.swing.DefaultComboBoxModel; 

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Luciano Pinedo
 */
public class Interfaz extends javax.swing.JFrame {
public static SistemaMemoria app; 
public static  Interfaz interfaz = new Interfaz(); 
private procesoNuevo procesonuevo = new procesoNuevo();
private DefaultTableModel modeloOriginal; 
public static ordenEjecucion ordenejecucion = new ordenEjecucion();


    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        
        initComponents();
        app = new SistemaMemoria(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel1.setText("Agregar proceso: ");

        jButton2.setText("Secuencial");

        jButton3.setText("Variada");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar Proceso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Memoria Principal");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Marco", "Proceso", "Pagina"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Memoria Virtual"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Proceso", "Número de Páginas", "Páginas Principal", "Páginas Virtual", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jLabel3.setText("Proceso a Ejecutar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
      procesonuevo.setVisible(true); 
      
          
      
      
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         String proceso = (String) jComboBox1.getSelectedItem(); 
        String[] division = proceso.split(":"); 
        int numeroProceso = Integer.parseInt(division[1].trim()); 
        app.ejecutarProceso(app.buscarProceso(numeroProceso));
        for (int i = 0; i < app.getMemoriaPrincipal().getTamaño(); i++) {
            if (app.getMemoriaPrincipal().getMemoriaPrincipal()[i] != null) {
            System.out.println("[" + app.getMemoriaPrincipal().getMemoriaPrincipal()[i].getNumeroPagina() + "]");
            }
            
        }
        actualizarMemoriaPrincipal(); 
        if (app.revisarFinal(app.buscarProceso(numeroProceso))) {
             try {
                 app.finalizarProceso(app.buscarProceso(numeroProceso));
             } catch (InterruptedException ex) {
                 Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
             }
            removerMemoriaPrincipal(numeroProceso); 
            
        };
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public  void actualizarLista() {
      DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel(); 
      int ultimo = app.getMemoriaVirtual().getProcesosVirtual().size() - 1;
      
            if (ultimo != -1) {
            int numero = app.getMemoriaVirtual().getProcesosVirtual().get(ultimo).getNumeroProceso();
            model.addRow(new Object[] { "Proceso " + Integer.toString(numero)});
            }
    }
    
    public void actualizarMemoriaPrincipal() {
        
        DefaultTableModel memoriaTablaDinamica = modeloOriginal; 
        for (int i = 0; i < app.getMemoriaPrincipal().getTamaño();  i++) {
            if (app.getMemoriaPrincipal().getMemoriaPrincipal()[i] != null) {
            String proceso = "Proceso " + app.getMemoriaPrincipal().getMemoriaPrincipal()[i].getProcesoPadre().getNumeroProceso();
            String pagina  = "Pagina "  + app.getMemoriaPrincipal().getMemoriaPrincipal()[i].getNumeroPagina(); 
            memoriaTablaDinamica.setValueAt(proceso, i, 1); 
            memoriaTablaDinamica.setValueAt(pagina, i , 2); 
        }
        }
        
        jTable2.setModel(memoriaTablaDinamica); 
    }
    
    public void removerMemoriaPrincipal(int numProceso) {
        DefaultTableModel memoriaTablaDinamica = modeloOriginal; 
        String proceso = "Proceso " + numProceso;
        for (int i = 0; i < app.getMemoriaPrincipal().getTamaño(); i++) {
        if (modeloOriginal.getValueAt(i, 1).equals(proceso)) {
            modeloOriginal.setValueAt("",i ,1);
            modeloOriginal.setValueAt("", i, 2); 
        }
            }
    }
    public void actualizarComboBox() {
        
        DefaultComboBoxModel comboBoxDinamico = new DefaultComboBoxModel(); 
        for (int i = 0; i < app.getAllProcesos().size(); i++) {
            String labelProceso = "Proceso: " + app.getAllProcesos().get(i).getNumeroProceso(); 
            comboBoxDinamico.addElement(labelProceso);
        }
        jComboBox1.setModel(comboBoxDinamico);
        
    }
    
    public void actualizarTodo() {
        
        actualizarLista();  
        actualizarComboBox(); 
        actualizarMemoriaPrincipal(); 
    }
    
    public void iniciar() {
        
         modeloOriginal = (DefaultTableModel) jTable2.getModel(); 
         for (int i = 0; i < app.getMemoriaPrincipal().getTamaño(); i++) {
  
           
                modeloOriginal.addRow(new Object[] {Integer.toString(i), "", ""}
                        
                );
        }
    }
    
    public static void main(String args[]) throws InterruptedException {
       Inicio inicio = new Inicio();  
     
      
       inicio.setVisible(true);
       while (!inicio.isIniciado()) {
       Thread.sleep(200); 
         
        
       }
       
        inicio.setVisible(false); 
        interfaz.setVisible(true);
        
        app.iniciar(inicio.enviarInicial()); 
        interfaz.iniciar(); 
      
       
       
  
        
        
        
        
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        }); */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
