/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import sistemamemoria.SistemaMemoria; 
/**
 *
 * @author Luciano Pinedo
 */
public class Interfaz extends javax.swing.JFrame {
public static SistemaMemoria app; 
procesoNuevo procesonuevo = new procesoNuevo();
ordenEjecucion ordenejecucion = new ordenEjecucion();
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        procesonuevo.setDefaultCloseOperation(procesonuevo.DISPOSE_ON_CLOSE); 
        ordenejecucion.setDefaultCloseOperation(ordenejecucion.DISPOSE_ON_CLOSE);
        initComponents();
        app = new SistemaMemoria(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar Proceso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
      procesonuevo.setVisible(true); 
      
      if (procesonuevo.isCreado()) {
          
          if (procesonuevo.isSecuencial()) {
              System.out.println("Hola");
              app.crearProcesoSecuencial(procesonuevo.getNumPag()); 
              procesonuevo.setCreado(false);
              procesonuevo.setSecuencial(false); 
          }
          
      }
      
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
       Inicio inicio = new Inicio();  
       Interfaz interfaz = new Interfaz(); 
       
       inicio.setVisible(true);
       while (!inicio.isIniciado()) {
       Thread.sleep(200); 
         
        
       }
       
        inicio.setVisible(false); 
        interfaz.setVisible(true); 
        app.iniciar(inicio.enviarInicial()); 
        
        
       
       
  
        
        
        
        
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        }); */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
